from django.urls import path, include
from TP import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
	path('registration', views.create_user, name = 'create_user'),
    path('login', views.login_user, name = 'login_user'),
	path('sammtuci', views.sammtuci, name = 'sammtuci'),
	path('create_branch', views.create_branch, name = 'create_branch'),
	path('read_branch', views.read_branch, name = 'read_branch'),
	path('update_branch', views.update_branch, name = 'update_branch'),
	path('delete_branch', views.delete_branch, name = 'delete_branch'),
	path('create_faculty', views.create_faculty, name = 'create_faculty'),
	path('read_faculty', views.read_faculty, name = 'read_faculty'),
	path('update_faculty', views.update_faculty, name = 'update_faculty'),
	path('delete_faculty', views.delete_faculty, name = 'delete_faculty'),
	path('create_department', views.create_department, name = 'create_department'),
	path('read_department', views.read_department, name = 'read_department'),
	path('update_department', views.update_department, name = 'update_department'),
	path('delete_department', views.delete_department, name = 'delete_department'),
	path('create_usertype', views.create_usertype, name = 'create_usertype'),
	path('read_usertype', views.read_usertype, name = 'read_usertype'),
	path('update_usertype', views.update_usertype, name = 'update_usertype'),
	path('delete_usertype', views.delete_usertype, name = 'delete_usertype'),
    path('create_deaneryuser', views.create_deaneryuser, name = 'create_deaneryuser'),
	path('read_deaneryuser', views.read_deaneryuser, name = 'read_deaneryuser'),
	path('update_deaneryuser', views.update_deaneryuser, name = 'update_deaneryuser'),
	path('delete_deaneryuser', views.delete_deaneryuser, name = 'delete_deaneryuser'),
	path('create_mark', views.create_mark, name = 'create_mark'),
	path('read_mark', views.read_mark, name = 'read_mark'),
	path('update_mark', views.update_mark, name = 'update_mark'),
	path('delete_mark', views.delete_mark, name = 'delete_mark'),
	path('create_year', views.create_year, name = 'create_year'),
	path('read_year', views.read_year, name = 'read_year'),
	path('update_year', views.update_year, name = 'update_year'),
	path('delete_year', views.delete_year, name = 'delete_year'),
	path('create_presenttype', views.create_presenttype, name = 'create_presenttype'),
	path('read_presenttype', views.read_presenttype, name = 'read_presenttype'),
	path('update_presenttype', views.update_presenttype, name = 'update_presenttype'),
	path('delete_presenttype', views.delete_presenttype, name = 'delete_presenttype'),
	path('create_group', views.create_group, name = 'create_group'),
	path('read_group', views.read_group, name = 'read_group'),
	path('update_group', views.update_group, name = 'update_group'),
	path('delete_group', views.delete_group, name = 'delete_group'),
	path('create_teacher', views.create_teacher, name = 'create_teacher'),
	path('read_teacher', views.read_teacher, name = 'read_teacher'),
	path('update_teacher', views.update_teacher, name = 'update_teacher'),
	path('delete_teacher', views.delete_teacher, name = 'delete_teacher'),
	path('create_student', views.create_student, name = 'create_student'),
	path('read_student', views.read_student, name = 'read_student'),
	path('update_student', views.update_student, name = 'update_student'),
	path('delete_student', views.delete_student, name = 'delete_student'),
	path('create_subject', views.create_subject, name = 'create_subject'),
	path('read_subject', views.read_subject, name = 'read_subject'),
	path('update_subject', views.update_subject, name = 'update_subject'),
	path('delete_subject', views.delete_subject, name = 'delete_subject'),
	path('create_subjectduringyear', views.create_subjectduringyear, name = 'create_subjectduringyear'),
	path('read_subjectduringyear', views.read_subjectduringyear, name = 'read_subjectduringyear'),
	path('update_subjectduringyear', views.update_subjectduringyear, name = 'update_subjectduringyear'),
	path('delete_subjectduringyear', views.delete_subjectduringyear, name = 'delete_subjectduringyear'),
	path('create_task', views.create_task, name = 'create_task'),
	path('read_task', views.read_task, name = 'read_task'),
	path('update_task', views.update_task, name = 'update_task'),
	path('delete_task', views.delete_task, name = 'delete_task'),
	path('create_present', views.create_present, name = 'create_present'),
	path('read_present', views.read_present, name = 'read_present'),
	path('update_present', views.update_present, name = 'update_present'),
	path('delete_present', views.delete_present, name = 'delete_present'),
	path('create_taskgive', views.create_taskgive, name = 'create_taskgive'),
	path('read_taskgive', views.read_taskgive, name = 'read_taskgive'),
	path('teacher_read_student', views.teacher_read_student, name = 'teacher_read_student'),
	path('teacher_read_subjectduringyear', views.teacher_read_subjectduringyear, name = 'teacher_read_subjectduringyear'),
	path('student_read_task', views.student_read_task, name = 'student_read_task'),
	path('teacher_read_taskgive', views.teacher_read_taskgive, name = 'teacher_read_taskgive'),
	path('teacher_update_taskgive', views.teacher_update_taskgive, name = 'teacher_update_taskgive'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

